### ISSUE TITLE
v1.13.0 packer build fails during powershell executions

### ISSUE THREAD

**Issue by AlanHale25** [hashicorp/packer#13390]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When using packer v1.13.0 in Github Actions, it fails when executing powershell scripts. The same scripts work fine in v1.12.0.

#### Reproduction Steps

- Setup packer in github actions using the latest (v1.13.0)
- Attempt to executed a powershell script within a powershell provisioner

### Packer version

From `v1.13.0`

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.
I can not post due to enterprise security reasons. (I love my job)

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

Linux container runner

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by kp2099** [comment]
Hi @AlanHale25,
We’ve updated the way PowerShell scripts are executed starting with v1.13.0. Please see the changes in this PR: https://github.com/hashicorp/packer/pull/13334

Could you provide a minimal, reproducible Packer template along with debug logs (set PACKER_LOG=1) to help us better understand the issue? Thank you!

**Comment by dereklwood** [comment]
I'm seeing this as well.  Sorry I don't have a template to provide, but I have more info:

For build steps using the `script` element (not `inline`), the remote powershell execution environment does not have any environment variables set (not even the defaults such as `PACKER_BUILD_NAME`).

It looks like the changes in #13334 drop the variables in the defaultExecuteCommand [here](https://github.com/hashicorp/packer/pull/13334/files#diff-d14a08bdd4220845d76ed72a39e2c14537d31b0bdcb4118b3906d41db6fa2f07L115).  The setting of the variables was moved to the new wrapper, but that wrapper only gets used in `extractScript`, which is only called when an `inline` configuration is defined.

**Comment by CSpellmanKrieg** [comment]
I can also confirm we saw this yesterday.

Inlines LF seemed off because it would turn it into a single string.  env_vars not populated.  The output on the screen also changed from bright green and dark green to just bright green.  For the time being, we have to pin to the previous version.  Windows/Powershell needs to be part of the standard testing because I feel like this could have easily been caught.

**Comment by icarusdes** [comment]
Same here! 

I have 

```
  # Export AMI-specific environment variables
  provisioner "powershell" {
    inline = [
      "setx BUILD_AMI_VERSION \"${var.jenkins_build_id}\"",
      "setx BUILD_AMI_NAME \"${local.ami_name}\"",
      "setx BUILD_AMI_COMMIT \"${var.hash}\"",
    ]
  }
```

In the logs i see: 

```
13:17:04  2025/06/03 11:17:03 packer-provisioner-powershell plugin: Found command: setx BUILD_AMI_VERSION "2978"
13:17:04  2025/06/03 11:17:03 packer-provisioner-powershell plugin: Found command: setx BUILD_AMI_NAME "win32-build-v2978@20250603-105204"
13:17:04  2025/06/03 11:17:03 packer-provisioner-powershell plugin: Found command: setx BUILD_AMI_COMMIT "ea7a3afe96b8b27cb567f363337ac1f391a45173"
```

But later on i get: 

```
ERROR: Invalid syntax. Default option is not allowed more than '2' time(s).
Type "SETX /?" for usage.
```

With 1.12.0 it worked just fine seeing `SUCCESS: Specified value was saved.` three times, as expected for each set calls.

**Comment by kp2099** [comment]
We apologize for the regression that was introduced with this change. We are trying to get a working fix for the issues mentioned. Thank you for your understanding and patience.

**Comment by kp2099** [comment]
Hi @dereklwood @icarusdes 
I've opened a PR that aims to address the problem: https://github.com/hashicorp/packer/pull/13396/files.
Would you be open to testing it with the proposed changes to see if the issue is resolved on your end?

**Comment by icarusdes** [comment]
@kp2099 If you can give me a docker tag which I can simply drop into the place of `hashicorp/packer:light-1.12.0` we started using, yes i can check if the issue is resolved for us.

**Comment by kp2099** [comment]
Hi @icarusdes — that would require us to do a patch release that includes the proposed changes. Before moving forward with that, I’d like to get feedback from the community to confirm whether these changes adequately address the concerns raised.

If anyone would like to build Packer locally to test the changes, here’s a quick reference:

1. Install Go 
2. Clone the Packer repository and apply the changes from the PR.
3. Run `make dev` from the root of the repo.

Note: The`make dev` command installs the development Packer binary to `$GOPATH/bin` using go install. Make sure your `$PATH` is set up to prioritize `$GOPATH/bin` so that when you run `packer build`, it uses your local dev build.

**Comment by dereklwood** [comment]
I'm also unable to easily test this due to enterprise restrictions unfortunately.  My test would be pretty simple though, just ensuring the `environment_vars` configuration still actually sets the environment variables when using `script`.  Thanks for the quick response though!

**Comment by cotyhamilton** [comment]
I had issues on `Packer 1.13.0` from working `Packer 1.12.0`

This is now working on `Packer v1.13.1-dev` from your PR

```hcl
build {
  sources = [
    "source.azure-arm.db_2019",
    "source.azure-arm.db_2022"
  ]

  # copy sql script to machine
  provisioner "file" {
    source      = "./setup.sql"
    destination = "C:\\Temp\\"
  }

  # configuration
  provisioner "powershell" {
    environment_vars = [
      "SAPassword=${var.blah_db_sa_password}"
    ]
    inline = [
      "while ((Get-Service MSSQLSERVER).Status -ne 'Running') { Write-Host 'SQL Server not ready...'; Start-Sleep 10 }",
      "Start-Sleep 30",
      "sqlcmd -v SAPassword=$env:SAPassword -i C:\\Temp\\setup.sql",
      "New-NetFirewallRule -DisplayName \"SQLServer default instance\" -Direction Inbound -LocalPort 1433 -Protocol TCP -Action Allow",
      "New-NetFirewallRule -DisplayName \"SQLServer Browser service\" -Direction Inbound -LocalPort 1434 -Protocol UDP -Action Allow"
    ]
  }

  # extend volume and generalize
  provisioner "powershell" {
    inline = [
      "$size = (Get-PartitionSupportedSize -DriveLetter 'C'); Resize-Partition -DriveLetter 'C' -Size $size.SizeMax",
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
      "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
    ]
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
  }
}
```

**Comment by kp2099** [comment]
> I'm also unable to easily test this due to enterprise restrictions unfortunately. My test would be pretty simple though, just ensuring the `environment_vars` configuration still actually sets the environment variables when using `script`. Thanks for the quick response though!

@dereklwood Thanks for the context. I’ve tested this scenario, and it should be resolved with the open PR, which we’re planning to merge soon. A patch release will follow shortly after.

**Comment by tivanov-qb** [comment]
@kp2099 was the fix added into 1.13 ? I'm still seeing issues with this version.. I have three different issues that I'm trying to fix and each of them is only present into 1.13
If I pin 1.12, everything succeeds on my end.

executing following commands

```
  provisioner "powershell" {
    inline = ["Uninstall-Package 'AWS Tools for Windows' -Force",
              "Install-Module AWS.Tools.Installer -AllowClobber -Force",
              "Install-AWSToolsModule Common,EC2,SimpleSystemsManagement,SecurityToken,CertificateManager,ElasticLoadBalancing,ElasticLoadBalancingV2,AutoScaling,S3,Cloudformation,SQS -CleanUp -Scope AllUsers -AllowClobber -Force"
            ]
  }
```

return this error:

```
12:36:26  1749116181,,ui,say,==> amazon-ebs.windows-L1-ami: Provisioning with Powershell...
12:36:26  1749116181,,ui,say,==> amazon-ebs.windows-L1-ami: Provisioning with powershell script: /var/tmp/powershell-provisioner3987919713
12:36:26  1749116185,,ui,say,==> amazon-ebs.windows-L1-ami:
12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami: C:\Windows\Temp\script-68416515-9e88-e364-f417-10cf1a366e31.ps1 : An error occurred: Cannot bind parameter because
12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami: parameter 'AllowClobber' is specified more than once. To provide multiple values to parameters that can accept
12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami: multiple values%!(PACKER_COMMA) use the array syntax. For example%!(PACKER_COMMA) "-parameter value1%!(PACKER_COMMA)value2%!(PACKER_COMMA)value3".
12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : NotSpecified: (:) [Write-Error]%!(PACKER_COMMA) WriteErrorException
12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException%!(PACKER_COMMA)script-68416515-9e88-e364-f417-10cf1a3
12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami:    66e31.ps1
```

so I go ahead and remove -AllowClobber (which I should not, this is one of the bugs it was implemented, I think)

then I start getting absolute non-sense error that I do not even think it exists in powershell?

```
17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: C:\Windows\Temp\script-6841ade8-49de-0933-3844-548542206723.ps1 : An error occurred: A parameter cannot be found that
17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: C:\Windows\Temp\script-6841ade8-49de-0933-3844-548542206723.ps1 : An error occurred: A parameter cannot be found that
17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: matches parameter name 'ForceInstall-Module'.
17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: matches parameter name 'ForceInstall-Module'.
17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : NotSpecified: (:) [Write-Error]%!!(MISSING)(PACKER_COMMA) WriteErrorException
17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : NotSpecified: (:) [Write-Error]%!(PACKER_COMMA) WriteErrorException
17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException%!!(MISSING)(PACKER_COMMA)script-6841ade8-49de-0933-3844-5485422
17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException%!(PACKER_COMMA)script-6841ade8-49de-0933-3844-5485422
17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:    06723.ps1
17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:    06723.ps1
17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:
```

I also see another weird behaviour (this might have been fixed already)
```
20:14:29  1749143669,,ui,say,==> amazon-ebs.windows-L1-ami: Provisioning with powershell script: windows2019/scripts/install_sql.ps1
20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: IMAGE_TYPE:
20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: Caught Error: You cannot call a method on a null-valued expression.
20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: At C:\Windows\Temp\script-6841d075-473b-fcf4-90b9-f6444fac3573.ps1:5 char:3
20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: +   throw "Caught Error: $_"
20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: +   ~~~~~~~~~~~~~~~~~~~~~~~~
20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : OperationStopped: (Caught Error: Y...ued expression.:String) []%!(PACKER_COMMA) RuntimeException
20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Caught Error: You cannot call a method on a null-valued expression.
```

^ I have a script with if condition based on the IMAGE_TYPE and I never had an issue packer executing this script.. it was simply not entering the condition, but now it does..

**Comment by kp2099** [comment]
> [@kp2099](https://github.com/kp2099) was the fix added into 1.13 ? I'm still seeing issues with this version.. I have three different issues that I'm trying to fix and each of them is only present into 1.13 If I pin 1.12, everything succeeds on my end.
> 
> executing following commands
> 
> ```
>   provisioner "powershell" {
>     inline = ["Uninstall-Package 'AWS Tools for Windows' -Force",
>               "Install-Module AWS.Tools.Installer -AllowClobber -Force",
>               "Install-AWSToolsModule Common,EC2,SimpleSystemsManagement,SecurityToken,CertificateManager,ElasticLoadBalancing,ElasticLoadBalancingV2,AutoScaling,S3,Cloudformation,SQS -CleanUp -Scope AllUsers -AllowClobber -Force"
>             ]
>   }
> ```
> 
> return this error:
> 
> ```
> 12:36:26  1749116181,,ui,say,==> amazon-ebs.windows-L1-ami: Provisioning with Powershell...
> 12:36:26  1749116181,,ui,say,==> amazon-ebs.windows-L1-ami: Provisioning with powershell script: /var/tmp/powershell-provisioner3987919713
> 12:36:26  1749116185,,ui,say,==> amazon-ebs.windows-L1-ami:
> 12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami: C:\Windows\Temp\script-68416515-9e88-e364-f417-10cf1a366e31.ps1 : An error occurred: Cannot bind parameter because
> 12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami: parameter 'AllowClobber' is specified more than once. To provide multiple values to parameters that can accept
> 12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami: multiple values%!(PACKER_COMMA) use the array syntax. For example%!(PACKER_COMMA) "-parameter value1%!(PACKER_COMMA)value2%!(PACKER_COMMA)value3".
> 12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : NotSpecified: (:) [Write-Error]%!(PACKER_COMMA) WriteErrorException
> 12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException%!(PACKER_COMMA)script-68416515-9e88-e364-f417-10cf1a3
> 12:36:26  1749116185,,ui,error,==> amazon-ebs.windows-L1-ami:    66e31.ps1
> ```
> 
> so I go ahead and remove -AllowClobber (which I should not, this is one of the bugs it was implemented, I think)
> 
> then I start getting absolute non-sense error that I do not even think it exists in powershell?
> 
> ```
> 17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: C:\Windows\Temp\script-6841ade8-49de-0933-3844-548542206723.ps1 : An error occurred: A parameter cannot be found that
> 17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: C:\Windows\Temp\script-6841ade8-49de-0933-3844-548542206723.ps1 : An error occurred: A parameter cannot be found that
> 17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: matches parameter name 'ForceInstall-Module'.
> 17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami: matches parameter name 'ForceInstall-Module'.
> 17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : NotSpecified: (:) [Write-Error]%!!(MISSING)(PACKER_COMMA) WriteErrorException
> 17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : NotSpecified: (:) [Write-Error]%!(PACKER_COMMA) WriteErrorException
> 17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException%!!(MISSING)(PACKER_COMMA)script-6841ade8-49de-0933-3844-5485422
> 17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException%!(PACKER_COMMA)script-6841ade8-49de-0933-3844-5485422
> 17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:    06723.ps1
> 17:47:10  1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:    06723.ps1
> 17:47:10  2025/06/05 14:47:07 1749134827,,ui,error,==> amazon-ebs.windows-L1-ami:
> ```
> 
> I also see another weird behaviour (this might have been fixed already)
> 
> ```
> 20:14:29  1749143669,,ui,say,==> amazon-ebs.windows-L1-ami: Provisioning with powershell script: windows2019/scripts/install_sql.ps1
> 20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: IMAGE_TYPE:
> 20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: Caught Error: You cannot call a method on a null-valued expression.
> 20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: At C:\Windows\Temp\script-6841d075-473b-fcf4-90b9-f6444fac3573.ps1:5 char:3
> 20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: +   throw "Caught Error: $_"
> 20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami: +   ~~~~~~~~~~~~~~~~~~~~~~~~
> 20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : OperationStopped: (Caught Error: Y...ued expression.:String) []%!(PACKER_COMMA) RuntimeException
> 20:14:32  1749143672,,ui,say,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : Caught Error: You cannot call a method on a null-valued expression.
> ```
> 
> ^ I have a script with if condition based on the IMAGE_TYPE and I never had an issue packer executing this script.. it was simply not entering the condition, but now it does..

Hi @tivanov-qb we have released a patch 1.13.1. I think this should be addressed in that patch. Let me know if you are still facing any issues. Thank you!

**Comment by icarusdes** [comment]
@kp2099 We have checked `1.13.1` and it resolved our issue. Thanks for quickly jumping on it and solving the problem.

**Comment by tivanov-qb** [comment]
@kp2099 thank you for the quick reply! 1.13.1 works on my end too. However, I still see error when executing powershell script. This is not happening in 1.12 version

```
13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: param : The term 'param' is not recognized as the name of a cmdlet%!(PACKER_COMMA) function%!(PACKER_COMMA) script file%!(PACKER_COMMA) or operable program. Check
13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: the spelling of the name%!(PACKER_COMMA) or if a path was included%!(PACKER_COMMA) verify that the path is correct and try again.
13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: At C:\Windows\Temp\script-6842c2ba-50ae-5953-9687-12b936b8f376.ps1:1 char:212
13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: + ... R_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="windows-L1-ami"; param (
13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: +                                                                   ~~~~~
13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : ObjectNotFound: (param:String) []%!(PACKER_COMMA) CommandNotFoundException
13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : CommandNotFoundException
```

this is how I execute the script in provisioner:

```
  provisioner "powershell" {
    elevated_password = "${var.winrm_password}"
    elevated_user     = "${var.winrm_username}"
    scripts           = ["windows2019/scripts/InstallPowerShellModules.ps1"]
  }
```

and here is snipped from the `InstallPowerShellModules.ps1` script:

```
param (
	[Parameter(Mandatory=$false)]
    $force = $true
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$Credentials =

Write-Host "Enable TLS1.2 for this session.."
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Write-Host "Installing NuGet package provider ..."
```

**Comment by kp2099** [comment]
> [@kp2099](https://github.com/kp2099) thank you for the quick reply! 1.13.1 works on my end too. However, I still see error when executing powershell script. This is not happening in 1.12 version
> 
> ```
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: param : The term 'param' is not recognized as the name of a cmdlet%!(PACKER_COMMA) function%!(PACKER_COMMA) script file%!(PACKER_COMMA) or operable program. Check
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: the spelling of the name%!(PACKER_COMMA) or if a path was included%!(PACKER_COMMA) verify that the path is correct and try again.
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: At C:\Windows\Temp\script-6842c2ba-50ae-5953-9687-12b936b8f376.ps1:1 char:212
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: + ... R_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="windows-L1-ami"; param (
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: +                                                                   ~~~~~
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : ObjectNotFound: (param:String) []%!(PACKER_COMMA) CommandNotFoundException
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> this is how I execute the script in provisioner:
> 
> ```
>   provisioner "powershell" {
>     elevated_password = "${var.winrm_password}"
>     elevated_user     = "${var.winrm_username}"
>     scripts           = ["windows2019/scripts/InstallPowerShellModules.ps1"]
>   }
> ```
> 
> and here is snipped from the `InstallPowerShellModules.ps1` script:
> 
> ```
> param (
> 	[Parameter(Mandatory=$false)]
>     $force = $true
> )
> 
> $ErrorActionPreference = 'Stop'
> $ProgressPreference = 'SilentlyContinue'
> $Credentials =
> 
> Write-Host "Enable TLS1.2 for this session.."
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
> Write-Host "Installing NuGet package provider ..."
> ```

Hi @tivanov-qb, starting with Packer v1.13, we changed how PowerShell scripts are executed. Scripts are now run using the `-File` operator, and Packer generates a temporary file that includes some preamble logic before inserting your script content.

Here’s what gets prepended to the temp file:

1. A check to set the global:ProgressPreference:
i.e.
```
if (Test-Path variable:global:ProgressPreference)` +
		`{set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};
```
2. Debug mode (if enabled in the template):
```
Set-PsDebug -Trace <debug_mode>;
```
3. Environment variables are injected.
4. Your script content is appended at the end.

Since your `InstallPowerShellModules.ps1` uses a `param` block at the top level, this change causes the script to fail—param must appear at the beginning of the file, but it no longer does after the injected code.

To fix this, we recommend wrapping your script logic inside a function, and calling that function at the end. Here's an example:

```
# Conditional logic that is prepended to the file
if (Test-Path variable:global:ProgressPreference) {
    Set-Variable -Name variable:global:ProgressPreference -Value 'SilentlyContinue'
}

# Debug mode (if enabled in the template)

# Environment variables

# Script content

function Main {
    param (
        [Parameter(Mandatory=$false)]
        $force = $true
    )

    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'
    $Credentials =

    Write-Host "Force is: $force"
    Write-Host "Enable TLS1.2 for this session.."
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Write-Host "Installing NuGet package provider ..."
}

# Manually parse script arguments
$force = $true
for ($i = 0; $i -lt $args.Count; $i += 2) {
    if ($args[$i] -ieq '-force') {
        $force = [bool]::Parse($args[$i + 1])
    }
}

Main -force:$force

```
I tested this approach with -File, and it works as expected. Let me know if you’d like help adapting your script this way.

```
PS C:\Users\karthik.karthik\Desktop> powershell -executionpolicy bypass -File test_file.ps1 -force $false
Force is: False
Enable TLS1.2 for this session..
Installing NuGet package provider ...

PS C:\Users\karthik.karthik\Desktop> powershell -executionpolicy bypass -File test_file.ps1 
Force is: True
Enable TLS1.2 for this session..
Installing NuGet package provider ...
```

**Comment by kp2099** [comment]
> [@kp2099](https://github.com/kp2099) thank you for the quick reply! 1.13.1 works on my end too. However, I still see error when executing powershell script. This is not happening in 1.12 version
> 
> ```
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: param : The term 'param' is not recognized as the name of a cmdlet%!(PACKER_COMMA) function%!(PACKER_COMMA) script file%!(PACKER_COMMA) or operable program. Check
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: the spelling of the name%!(PACKER_COMMA) or if a path was included%!(PACKER_COMMA) verify that the path is correct and try again.
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: At C:\Windows\Temp\script-6842c2ba-50ae-5953-9687-12b936b8f376.ps1:1 char:212
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: + ... R_TYPE="amazon-ebs"; $env:PACKER_BUILD_NAME="windows-L1-ami"; param (
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami: +                                                                   ~~~~~
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami:     + CategoryInfo          : ObjectNotFound: (param:String) []%!(PACKER_COMMA) CommandNotFoundException
> 13:28:15  1749205695,,ui,say,==> amazon-ebs.windows-L1-ami:     + FullyQualifiedErrorId : CommandNotFoundException
> ```
> 
> this is how I execute the script in provisioner:
> 
> ```
>   provisioner "powershell" {
>     elevated_password = "${var.winrm_password}"
>     elevated_user     = "${var.winrm_username}"
>     scripts           = ["windows2019/scripts/InstallPowerShellModules.ps1"]
>   }
> ```
> 
> and here is snipped from the `InstallPowerShellModules.ps1` script:
> 
> ```
> param (
> 	[Parameter(Mandatory=$false)]
>     $force = $true
> )
> 
> $ErrorActionPreference = 'Stop'
> $ProgressPreference = 'SilentlyContinue'
> $Credentials =
> 
> Write-Host "Enable TLS1.2 for this session.."
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
> Write-Host "Installing NuGet package provider ..."
> ```

Hi @tivanov-qb, starting with Packer v1.13, we changed how PowerShell scripts are executed. Scripts are now run using the -File operator (for non elevated scripts, elevated scripts already use the -File operator), and Packer generates a temporary file that includes some preamble logic before inserting your script content.

Here’s what gets prepended to the temp file:

1. A check to set the global:ProgressPreference:

```
if (Test-Path variable:global:ProgressPreference) {
    Set-Variable -Name variable:global:ProgressPreference -Value 'SilentlyContinue'
}
```

2. Debug mode (if enabled in the template):

```
Set-PsDebug -Trace <debug_mode>
```

3. Environment variables are injected.

4. Your script content is appended at the end.

Since your `InstallPowerShellModules.ps1` uses a `param` block at the top level, this change causes the script to fail—param must appear at the beginning of the file, but it no longer does after the injected code.

To fix this, we recommend wrapping your script logic inside a function, and calling that function at the end. Here's an example:

```
function Main {
    param (
        [Parameter(Mandatory = $false)]
        $force = $true
    )

    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'
    $Credentials = $null

    Write-Host "Force is: $force"
    Write-Host "Enable TLS1.2 for this session.."
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Write-Host "Installing NuGet package provider ..."
}

# Parse arguments
$force = $true
for ($i = 0; $i -lt $args.Count; $i += 2) {
    if ($args[$i] -ieq '-force') {
        $force = [bool]::Parse($args[$i + 1])
    }
}

Main -force:$force
```

I tested this approach with -File, and it works as expected. 
```
PS C:\Users\karthik.karthik\Desktop> powershell -executionpolicy bypass -File test_file.ps1 -force $false
Force is: False
Enable TLS1.2 for this session..
Installing NuGet package provider ...

PS C:\Users\karthik.karthik\Desktop> powershell -executionpolicy bypass -File test_file.ps1 
Force is: True
Enable TLS1.2 for this session..
Installing NuGet package provider ...
```

here is the output from an example template i ran with the above change

```
2025/06/06 20:15:48 packer-plugin-amazon_v1.3.7_x5.0_darwin_arm64 plugin: 2025/06/06 20:15:48 Uploading file to 'c:/Windows/Temp/script-6842fee2-c53c-4fe8-0ff0-8ad4e870842c.ps1'
2025/06/06 20:16:22 packer-plugin-amazon_v1.3.7_x5.0_darwin_arm64 plugin: 2025/06/06 20:16:22 [INFO] starting remote command: powershell -executionpolicy bypass -file "C:/Windows/Temp/packer-elevated-shell-6842fefe-9a40-5ac3-9c03-e80923d9ef07.ps1"
==> learn-packer.amazon-ebs.windows-example: Force is: True
==> learn-packer.amazon-ebs.windows-example: Enable TLS1.2 for this session..
==> learn-packer.amazon-ebs.windows-example: Installing NuGet package provider ...
2025/06/06 20:16:56 packer-plugin-amazon_v1.3.7_x5.0_darwin_arm64 plugin: 2025/06/06 20:16:56 [INFO] command 'powershell -executionpolicy bypass -file "C:/Windows/Temp/packer-elevated-shell-6842fefe-9a40-5ac3-9c03-e80923d9ef07.ps1"' exited with code: 0

```

**Comment by tivanov-qb** [comment]
@kp2099 thank you for the detailed explanation and for your time on this one!

**Comment by JamesKindon** [comment]
I know this is a closed issue, but this is a pretty severe breaking change for anyone that uses PowerShell scripting heavily. This means that all well structured scripts, that serve multipurpose scenarios, are going to break and need to be re-written/factored to allow Packer to execute them? Ouch. 

What is the reason for changing this behavior after so long when it's been working for years?

**Comment by gabrielgbs97** [comment]
I also had problems with this new script transformation. It may be related to encoding issues, our scripts (.ps1 sources) are usually UTF16-LE encoded, this packs BOM and are signable/verifiable. Packer wrapping may start file as non-Unicode (no BOM), and recognized as such by Windows Powershell?

**Comment by kp2099** [comment]
Hi @gabrielgbs97 @JamesKindon we will be reverting the changes to default script execution. The change has already been merged in https://github.com/hashicorp/packer/pull/13422

We will release it with 1.14.0

The inline param would still use the -File operator, Script and Scripts will use the default execution command as of 1.12.0
