### ISSUE TITLE
Cloning is not supported with VMware WS version 9. Please use VMware WS version 10, or greater.

### ISSUE THREAD

**Issue by nbayle** [hashicorp/packer#5797]
I'm getting the error:
```
Build 'vmware-vmx' errored: Cloning is not supported with VMware WS version 9. Please use VMware WS version 10, or greater.
```

I'm using VMware Workstation Pro 14 on Debian 8.10. It is licensed. I have installed VIX.

```
packer --version
1.1.3

vmware-installer -t
Component Name                 Component Long Name                               Component Version   
============================== ================================================= ====================
vmware-installer               VMware Installer                                  2.1.0.7305623       
vmware-player-setup            VMware Player Setup                               14.1.1.7528167      
vmware-vmx                     VMware VMX                                        14.1.1.7528167      
vmware-vix-lib-Workstation1400 VMware VIX Workstation-14.0.0 Library             1.17.0.7528167      
vmware-vix-core                VMware VIX Core Library                           1.17.0.7528167      
vmware-network-editor          VMware Network Editor                             14.1.1.7528167      
vmware-network-editor-ui       VMware Network Editor User Interface              14.1.1.7528167      
vmware-tools-netware           VMware Tools for NetWare                          10.2.0.7528167      
vmware-tools-linuxPreGlibc25   VMware Tools for legacy Linux                     10.2.0.7528167      
vmware-tools-winPreVista       VMware Tools for Windows 2000, XP and Server 2003 10.2.0.7528167      
vmware-tools-winPre2k          VMware Tools for Windows 95, 98, Me and NT        10.2.0.7528167      
vmware-tools-freebsd           VMware Tools for FreeBSD                          10.2.0.7528167      
vmware-tools-windows           VMware Tools for Windows Vista or later           10.2.0.7528167      
vmware-tools-solaris           VMware Tools for Solaris                          10.2.0.7528167      
vmware-tools-linux             VMware Tools for Linux                            10.2.0.7528167      
vmware-usbarbitrator           VMware USB Arbitrator                             17.1.3.7528167      
vmware-player-app              VMware Player Application                         14.1.1.7528167      
vmware-workstation-server      VMware Workstation Server                         14.1.1.7528167      
vmware-ovftool                 VMware OVF Tool component for Linux               4.2.0.6230482       
vmware-vprobe                  VMware VProbes component for Linux                14.1.1.7528167      
vmware-workstation             VMware Workstation                                14.1.1.7528167      
```

Verbose log:
https://gist.github.com/nbayle/a53de08b38868cc9a4b8b158c325acd7

**Comment by nbayle** [comment]
Whelp, I hate being this guy, but is there a tip jar where I can.... escalate this? I tried to hunt down a support plan, but I guess that's not a thing.

**Comment by mwhooker** [comment]
Can you tell me the output of `/usr/lib/vmware/bin/vmware-vmx -v`

**Comment by mwhooker** [comment]
I've pushed some code to make debugging this easier. Will you please compile from master, rerun, and post the output with debug logging turned on?

**Comment by nbayle** [comment]
The output was 

```
/usr/lib/vmware/bin/vmware-vmx -v
/usr/lib/vmware/bin/vmware-vmx: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
```

So I installed libXtst & x11-common and the output is:
```
VMware Workstation Information:
VMware Workstation 14.1.1 build-7528167 Release
```

Now when I run packer the error has changed:
```
2018/01/27 19:15:38 packer: 2018/01/27 19:15:38 Cloning to: output-vmware-vmx/packer-vmware-vmx-1517109338.vmx
2018/01/27 19:15:38 packer: 2018/01/27 19:15:38 Executing: /usr/bin/vmrun -T ws clone /home/nicholas/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/201801.02.0/vmware_desktop/ubuntu-16.04-amd64.vmx output-vmware-vmx/packer-vmware-vmx-1517109338.vmx full
2018/01/27 19:15:39 packer: 2018/01/27 19:15:39 stdout: Unable to connect to host.
2018/01/27 19:15:39 packer: Error: The specified version was not found
```

**Comment by nbayle** [comment]
Any ideas?

Google says the solution is to update the /var/lib/vmware/vixwrapper-product-config.txt file with the correct version numbers, but it's already up to date and doesn't resolve this.

**Comment by mwhooker** [comment]
those don't look like packer errors and it's impossible to say without fuller logs.

What does `/usr/bin/vmrun -T ws clone /home/nicholas/.vagrant.d/boxes/bento-VAGRANTSLASH-ubuntu-16.04/201801.02.0/vmware_desktop/ubuntu-16.04-amd64.vmx output-vmware-vmx/packer-vmware-vmx-1517109338.vmx full` say when you run it? assuming the vmx exists

**Comment by nbayle** [comment]
Closing this. I wiped everything out and reinstalled 14.1.1 *without* installing VIX separately and now everything works. VMware must be including vmrun with the main installer or something. At this point I'm just hitting bug #5882.
