### ISSUE TITLE
1.3.1 Build 'digitalocean' errored: unexpected EOF

### ISSUE THREAD

**Issue by webchi** [hashicorp/packer#6846]
- Packer version:  v1.3.1
- Host platform Ubuntu 17.10
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/webchi/d6d3c3d46ed2fbe8748fac0e1ac56029
- The _simplest example template and scripts_ needed to reproduce the bug.
 ```{
  "builders": [
    {
      "type": "digitalocean",
      "api_token": "API-TOKEN-OR-DIGITALOCEAN_API_TOKEN-SET",
      "image": "ubuntu-16-04-x64",
      "region": "nyc3",
      "size": "512mb",
      "ssh_username": "root"
    }
  ]
}
```

- Short error
```
digitalocean output will be in this color.

Build 'digitalocean' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> digitalocean: unexpected EOF

==> Builds finished but no artifacts were created.
```

**Comment by webchi** [comment]
Everything working with 1.2.5

**Comment by rickard-von-essen** [comment]
Duplicates #6715 which is already fixed on master.

**Comment by ksanderer** [comment]
Hey, guys! I'm still getting the error while downloading binaries from https://www.packer.io/downloads.html

Could you please update download section to the latest release?

**Comment by webchi** [comment]
Fixed version is not yet realeased. I've build new version from git https://www.packer.io/intro/getting-started/install.html#compiling-from-source
