### ISSUE TITLE
ebs-surrogate: now creates 3 snapshots, in 1.2.2 it created 1

### ISSUE THREAD

**Issue by spacharya** [hashicorp/packer#6897]
We were using ebs-surrogate to create an ami of one volume on a machine with multiple volumes(3 volumes).
It worked fine till version 1.2.2.
In version 1.2.2 the docs got updated by this commit : https://github.com/hashicorp/packer/commit/d3848903e046dcd3473d2debe289bad1d8f79731
Then a github issue was opened https://github.com/hashicorp/packer/pull/6056
Since the documentation and the behviour was different, the behaviour was updated.
However, this broke the usage prior to version 1.2.3
Now on using ebs-surrogate we get 3 snapshots and 3 volumes in our AMI instead of 1.

A sample script of packer call is https://gist.github.com/spacharya/3f2a3efac890478ca5ec6a2eb616c53c

Request : Either revert to the old behaviour. (might break compatibility for a few) Or provide a path to regain the same behviour either through some flag or an alternate builder.

**Comment by rickard-von-essen** [comment]
This was correcting the intended behaviour of the `ebs-surrogate` builder, bringing it in line with other Amazon builders.

**Comment by rickard-von-essen** [comment]
Can you describe why you need this? So we understand your use case.

**Comment by spacharya** [comment]
Okay.
But still is it possible to have the old behaviour back? It is preventing upgrades for us.

The main reason we use this is for formatting our amis in such a way they are optimized to begin with.
We went with this documentation from AWS https://aws.amazon.com/blogs/apn/how-to-build-sparse-ebs-volumes-for-fun-and-easy-snapshotting/ and the way to go about it seemed to be using the surrogate and just dd the image over to another volume therby trimming the volume.

**Comment by rickard-von-essen** [comment]
That sounds as a legit use case. We can probably add a flag for not including the volume in the AMI.

**Comment by spacharya** [comment]
Thanks. In another thread another user also has mentioned it is needed for him. 
The gist as provided will show different behaviour in 1.2.2 and 1.2.3

**Comment by matthack** [comment]
Friendly ping, this is something that is still affecting us and causing us to be on an older version of Packer where we frequently get rate limited AWS EBS.

**Comment by SwampDragons** [comment]
Sorry we haven't gotten to this yet; with over 400 open issues and only two full time maintainers, there's just a lot on our plates. PRs are always welcome if you're in a rush for a fix.

**Comment by azr** [comment]
Hello there, I think this issue could have been fixed by #6787 that has been recently merged into master. Can someone please confirm this for me ? Otherwise I'll try to see what I can do.

**Comment by matthack** [comment]
Hi @azr, thanks for reaching out.

I tested using the binaries you posted on Dec 17 2018 on #6787 and I'm still seeing the undesired behavior of 3 snapshots getting created with the ebs-surrogate provider.

**Comment by SwampDragons** [comment]
This should be resolved by #7612, which allows you to set a flag that will not add launch block devices to amis.
