### ISSUE TITLE
launch_block_device_mappings: InvalidBlockDeviceMapping: the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.

### ISSUE THREAD

**Issue by dan-at-teza** [hashicorp/packer#7035]
I'm attempting to increase the size of my root partition from 8GB to 48GB with 'launch_block_device_mappings', but I run into the following error:

Build 'amazon-ebs' errored: Error launching source instance: InvalidBlockDeviceMapping: the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.

This looks like a repeat of Issue #2285.

- Packer version
$ packer version
Packer v1.3.2
- Host platform
$ uname -a
Darwin grixis 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- Debug log output from `PACKER_LOG=1 packer build template.json`.
https://gist.github.com/dan-at-teza/94560c5835d8eca2c30364fde3d29f26
- The _simplest example template and scripts_ needed to reproduce the bug.
https://gist.github.com/dan-at-teza/f8daf8f8bc745b4dab11e64a8b94d77e

**Comment by azr** [comment]
Hey @dan-at-teza, your issue should be fixed by the binaries of this PR: https://github.com/hashicorp/packer/pull/6787#issuecomment-441595804

This PR allows to not set the `launch_block_device_mappings.encrypted` setting.
It should probably be okay for your buildfile since the drive is immediately deleted;

please tell me if this fixes your issue 🙂

**Comment by dan-at-teza** [comment]
@azr, even with your PR, I still encounter the same problem.

It is already possible in packer version 1.3.2 to not set the encrypted flag, but then I end up with an unencrypted root partition. The issue that I reported was that I'm not able to create an encrypted root partition, and I think that it should be possible in AWS.

**Comment by azr** [comment]
@dan-at-teza, Sorry I didn't make myself clear enough.
#6787 is not merged in yet, so in packer 1.3.2 if you don't set the `encrypted` or `encrypt_boot` setting they are actually passed as `false`.
When building using #6787; not specifing them allows to keep the setting of the source image or snapshot. Which is something aws recently changed.

The error you get is ` the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.` This is just telling you you can't pass an encryption setting to `/dev/sda1` since it comes from a snapshot. 

If you want to encrypt your root partition you should just build using the binaries of #6787 with:
```json
    "launch_block_device_mappings": [{
	    "delete_on_termination": true,
	    "device_name": "/dev/sda1",
	    "volume_type": "gp2",
	    "volume_size": 48
    }],
    "encrypt_boot": true,
```
After doing this; I got an AMI with an encrypted drive: 

<img width="1091" alt="screenshot 2018-11-27 at 10 34 42" src="https://user-images.githubusercontent.com/1024852/49072303-38cb4e00-f230-11e8-8b1b-bd90d17dc07a.png">

**Comment by dan-at-teza** [comment]
Thanks, encrypt_boot was the missing bit that I needed.

-Dan

**Comment by SwampDragons** [comment]
Closing since this is a duplicate and has been solved in master branch.

**Comment by azr** [comment]
Also FYI, #6787 just got merged
