### ISSUE TITLE
shared_image_gallery_destination timeout issue

### ISSUE THREAD

**Issue by jontreynes** [hashicorp/packer#8445]
I am using Azure DevOps task, [PackerBuild@1](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops), with a customTemplate to build my image. The task runs successfully without shared_image_gallery_destination resource.

When I add the below code
`      "shared_image_gallery_destination": {

        "resource_group":"myrg",

        "gallery_name": "mygallery",

        "image_name": "myimage",

        "image_version": "3.0.0",

        "replication_regions": ["eastus"]

    },`
I receive the below timeout error

`Build 'azure-arm' errored: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded`

using version 1.4.5 like so:

``` 
- task: PackerBuild@1
      condition: true
      displayName: Build ${{ job.ibb_dest_sig_definition }} Custom Image
      inputs:
        templateType: 'custom'
        customTemplateLocation: '${{ job.ibb_customTemplateLocation }}'
        customTemplateParameters: # params
        connectedServiceName: ${{parameters.ibb_service_connection}}
        packerVersion: '1.4.5'
```

**Comment by jontreynes** [comment]
I'm referencing PR #7778 @amydutta

**Comment by jontreynes** [comment]
tagging contributors of this thread
https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/packer-build.md

@chcomley
@steved0x
@davidstaheli 
@alexhomer1

**Comment by jontreynes** [comment]
Update: It worked a second try with no changes in code. This seems to be flaky based on how long it takes to run.

1st try time out failed at 22 minutes.
2nd try was successful within 16 min 23s

**Comment by SwampDragons** [comment]
Thanks for the report. I've seen a couple of reports of these context timeouts, so it sounds like there may be something we can tweak internally to extend that deadline.

**Comment by nywilken** [comment]
hi @jontreynes we've made a fix to the Azure builder that may help with the issue you are seeing here. The fix involves the use of the `shared_image_gallery_timeout` configuration option that allows a user to override the wait time needed for replication to complete. The default time is 60 minutes if the option is not specified. You can try the fix by using a patched binary [available here] (https://circleci.com/gh/hashicorp/packer/25041#artifacts/containers/0) or wait until the fix is released.

**Comment by nywilken** [comment]
Hi @jontreynes I am going to close this issue, as I believe it was resolved by [Packer 1.5.1](https://www.packer.io/downloads.html). If you haven't already, please download the latest release of Packer and try your configuration again. 

 If you believe there's something wrong with Packer still, we can reopen and continue to investigate.

**Comment by alex-aosys** [comment]
Hi @nywilken we're still seeing this issue when deploying images into the shared image gallery, I've tried using both 1.5.1 and 1.5.3 and I get the same issue with both. I have `shared_image_gallery_timeout` set to 240m so I can't see that being the problem. Any ideas?

`2020-02-26T17:39:58Z: ==> azure-arm: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: cont│
ext deadline exceeded                                                                                                            │
2020-02-26T17:39:58Z: ==> azure-arm: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: cont│
ext deadline exceeded                                                                                                            │
2020-02-26T17:39:58Z: ==> azure-arm: Step "StepPublishToSharedImageGallery" failed`
